// Generated by dts-bundle-generator v9.5.1

/**
 * Типы для фабрик типов и схем контекста
 *
 * # Контекст (Context)
 *
 * Контекст — это типизированное состояние компонента, которое автоматически обновляет UI при изменениях.
 * Контекст должен содержать только простые типы данных: строки, числа, булевы значения, массивы и перечисления.
 *
 * ## Основные принципы:
 * - **Простота**: Используйте только простые типы в контексте
 * - **ID в массивах**: Массивы должны содержать только ID объектов
 * - **Сложные объекты в Core**: Сложные данные храните в core
 *
 * ## Поддерживаемые типы:
 * - `string` — строки
 * - `number` — числа
 * - `boolean` — булевы значения
 * - `array` — массивы (рекомендуется хранить только ID)
 * - `enum` — перечисления
 *
 * @example
 * ```typescript
 * .context((types) => ({
 *   // Обязательные поля
 *   name: types.string.required("Anonymous"),
 *   age: types.number.required(18),
 *   isActive: types.boolean.required(false),
 *
 *   // Опциональные поля
 *   email: types.string.optional(),
 *   avatar: types.string.optional(),
 *
 *   // Массивы (храним только ID)
 *   userIds: types.array.required([]),
 *
 *   // Enum
 *   status: types.enum.required(["pending", "active", "blocked"]),
 * }))
 * ```
 */
/**
 * Базовое определение строкового типа
 * @property type - Тип поля ("string")
 * @property title - Опциональное название поля для документации
 * @property default - Значение по умолчанию
 */
export interface BaseStringDefinition {
	type: "string";
	title?: string;
	default?: string | undefined;
}
/**
 * Базовое определение числового типа
 * @property type - Тип поля ("number")
 * @property title - Опциональное название поля для документации
 * @property default - Значение по умолчанию
 */
export interface BaseNumberDefinition {
	type: "number";
	title?: string;
	default?: number | undefined;
}
/**
 * Базовое определение булевого типа
 * @property type - Тип поля ("boolean")
 * @property title - Опциональное название поля для документации
 * @property default - Значение по умолчанию
 */
export interface BaseBooleanDefinition {
	type: "boolean";
	title?: string;
	default?: boolean | undefined;
}
/**
 * Базовое определение типа массива
 * @template T - Тип элементов массива (string, number, boolean)
 * @property type - Тип поля ("array")
 * @property title - Опциональное название поля для документации
 * @property default - Значение по умолчанию (массив)
 *
 * @example
 * ```typescript
 * // Массив строк (ID пользователей)
 * userIds: types.array.required([])
 *
 * // Массив чисел (ID постов)
 * postIds: types.array.required([])
 * ```
 */
export interface BaseArrayDefinition<T extends string | number | boolean> {
	type: "array";
	title?: string;
	default?: T[] | undefined;
}
/**
 * Базовое определение типа перечисления
 * @template T - Массив допустимых значений
 * @property type - Тип поля ("enum")
 * @property values - Массив допустимых значений
 * @property title - Опциональное название поля для документации
 * @property default - Значение по умолчанию
 *
 * @example
 * ```typescript
 * // Перечисление статусов
 * status: types.enum.required(["pending", "active", "blocked"])
 *
 * // Перечисление ролей
 * role: types.enum.required(["user", "admin", "moderator"])
 * ```
 */
export interface BaseEnumDefinition<T extends readonly (string | number)[]> {
	type: "enum";
	values: T;
	title?: string;
	default?: T[number] | undefined;
}
/**
 * Обязательное строковое поле
 * @example
 * ```typescript
 * name: types.string.required("Anonymous")
 * email: types.string.required("")
 * ```
 */
export interface RequiredStringDefinition extends BaseStringDefinition {
	required: true;
}
/**
 * Обязательное числовое поле
 * @example
 * ```typescript
 * age: types.number.required(18)
 * count: types.number.required(0)
 * ```
 */
export interface RequiredNumberDefinition extends BaseNumberDefinition {
	required: true;
}
/**
 * Обязательное булево поле
 * @example
 * ```typescript
 * isActive: types.boolean.required(false)
 * isLoading: types.boolean.required(false)
 * ```
 */
export interface RequiredBooleanDefinition extends BaseBooleanDefinition {
	required: true;
}
/**
 * Обязательное поле массива
 * @template T - Тип элементов массива
 * @example
 * ```typescript
 * // Массив ID пользователей
 * userIds: types.array.required([])
 *
 * // Массив ID постов
 * postIds: types.array.required([])
 * ```
 */
export interface RequiredArrayDefinition<T extends string | number | boolean> extends BaseArrayDefinition<T> {
	required: true;
}
/**
 * Обязательное поле перечисления
 * @template T - Массив допустимых значений
 * @example
 * ```typescript
 * status: types.enum.required(["pending", "active", "blocked"])
 * role: types.enum.required(["user", "admin"])
 * ```
 */
export interface RequiredEnumDefinition<T extends readonly (string | number)[]> extends BaseEnumDefinition<T> {
	required: true;
}
/**
 * Опциональное строковое поле
 * @example
 * ```typescript
 * description: types.string.optional()
 * avatar: types.string.optional()
 * ```
 */
export interface OptionalStringDefinition extends BaseStringDefinition {
	required: false;
}
/**
 * Опциональное числовое поле
 * @example
 * ```typescript
 * rating: types.number.optional()
 * priority: types.number.optional()
 * ```
 */
export interface OptionalNumberDefinition extends BaseNumberDefinition {
	required: false;
}
/**
 * Опциональное булево поле
 * @example
 * ```typescript
 * isVerified: types.boolean.optional()
 * isPremium: types.boolean.optional()
 * ```
 */
export interface OptionalBooleanDefinition extends BaseBooleanDefinition {
	required: false;
}
/**
 * Опциональное поле массива
 * @template T - Тип элементов массива
 * @example
 * ```typescript
 * tags: types.array.optional()
 * categories: types.array.optional()
 * ```
 */
export interface OptionalArrayDefinition<T extends string | number | boolean> extends BaseArrayDefinition<T> {
	required: false;
}
/**
 * Опциональное поле перечисления
 * @template T - Массив допустимых значений
 * @example
 * ```typescript
 * theme: types.enum.optional(["light", "dark"])
 * language: types.enum.optional(["ru", "en"])
 * ```
 */
export interface OptionalEnumDefinition<T extends readonly (string | number)[]> extends BaseEnumDefinition<T> {
	required: false;
}
/**
 * Объединенный тип для строковых определений
 */
export type StringDefinition = RequiredStringDefinition | OptionalStringDefinition;
/**
 * Объединенный тип для числовых определений
 */
export type NumberDefinition = RequiredNumberDefinition | OptionalNumberDefinition;
/**
 * Объединенный тип для булевых определений
 */
export type BooleanDefinition = RequiredBooleanDefinition | OptionalBooleanDefinition;
/**
 * Объединенный тип для определений массивов
 * @template T - Тип элементов массива (по умолчанию string)
 */
export type ArrayDefinition<T extends string | number | boolean = string> = RequiredArrayDefinition<T> | OptionalArrayDefinition<T>;
/**
 * Объединенный тип для определений перечислений
 * @template T - Массив допустимых значений
 */
export type EnumDefinition<T extends readonly (string | number)[]> = RequiredEnumDefinition<T> | OptionalEnumDefinition<T>;
/**
 * Объединенный тип для всех возможных определений типов
 */
export type AnyDefinition = StringDefinition | NumberDefinition | BooleanDefinition | ArrayDefinition<any> | EnumDefinition<any>;
/**
 * Схема контекста - объект, где ключи - это имена полей, а значения - определения типов
 *
 * @example
 * ```typescript
 * const schema: ContextSchema = {
 *   name: { type: "string", required: true, default: "Anonymous" },
 *   age: { type: "number", required: true, default: 18 },
 *   isActive: { type: "boolean", required: true, default: false },
 *   userIds: { type: "array", required: true, default: [] },
 *   status: { type: "enum", required: true, values: ["pending", "active"], default: "pending" }
 * }
 * ```
 */
export type ContextSchema = Record<string, AnyDefinition>;
/**
 * Фабрики типов для создания схем контекста
 * @example
 * ```typescript
 * types.string.required('Гость')
 * types.number.optional()
 * types.boolean.required()
 * types.array().optional()
 * types.enum('user', 'admin').required('user')
 * ```
 */
export type ContextTypes = {
	string: {
		required: <T extends string = string>(defaultValue?: T) => ((options?: {
			title?: string;
		}) => RequiredStringDefinition) & RequiredStringDefinition;
		optional: <T extends string = string>(defaultValue?: T) => ((options?: {
			title?: string;
		}) => OptionalStringDefinition) & OptionalStringDefinition;
		<T extends string = string>(defaultValue?: T): ((options?: {
			title?: string;
		}) => OptionalStringDefinition) & OptionalStringDefinition;
	};
	number: {
		required: <T extends number = number>(defaultValue?: T) => ((options?: {
			title?: string;
		}) => RequiredNumberDefinition) & RequiredNumberDefinition;
		optional: <T extends number = number>(defaultValue?: T) => ((options?: {
			title?: string;
		}) => OptionalNumberDefinition) & OptionalNumberDefinition;
		<T extends number = number>(defaultValue?: T): ((options?: {
			title?: string;
		}) => OptionalNumberDefinition) & OptionalNumberDefinition;
	};
	boolean: {
		required: <T extends boolean = boolean>(defaultValue?: T) => ((options?: {
			title?: string;
		}) => RequiredBooleanDefinition) & RequiredBooleanDefinition;
		optional: <T extends boolean = boolean>(defaultValue?: T) => ((options?: {
			title?: string;
		}) => OptionalBooleanDefinition) & OptionalBooleanDefinition;
		<T extends boolean = boolean>(defaultValue?: T): ((options?: {
			title?: string;
		}) => OptionalBooleanDefinition) & OptionalBooleanDefinition;
	};
	array: {
		required: <T extends string | number | boolean = string>(defaultValue?: T[]) => ((options?: {
			title?: string;
		}) => RequiredArrayDefinition<T>) & RequiredArrayDefinition<T>;
		optional: <T extends string | number | boolean = string>(defaultValue?: T[]) => ((options?: {
			title?: string;
		}) => OptionalArrayDefinition<T>) & OptionalArrayDefinition<T>;
		<T extends string | number | boolean = string>(defaultValue?: T[]): ((options?: {
			title?: string;
		}) => OptionalArrayDefinition<T>) & OptionalArrayDefinition<T>;
	};
	enum: <const T extends readonly (string | number)[]>(...values: T) => {
		required: (defaultValue?: T[number]) => ((options?: {
			title?: string;
		}) => RequiredEnumDefinition<T>) & RequiredEnumDefinition<T>;
		optional: (defaultValue?: T[number]) => ((options?: {
			title?: string;
		}) => OptionalEnumDefinition<T>) & OptionalEnumDefinition<T>;
		(defaultValue?: T[number]): ((options?: {
			title?: string;
		}) => OptionalEnumDefinition<T>) & OptionalEnumDefinition<T>;
	};
};
export type ExtractValue<T> = T extends RequiredStringDefinition ? string : T extends OptionalStringDefinition ? string | null : T extends RequiredNumberDefinition ? number : T extends OptionalNumberDefinition ? number | null : T extends RequiredBooleanDefinition ? boolean : T extends OptionalBooleanDefinition ? boolean | null : T extends RequiredArrayDefinition<infer U> ? U[] : T extends OptionalArrayDefinition<infer U> ? U[] | null : T extends RequiredEnumDefinition<infer U> ? U[number] : T extends OptionalEnumDefinition<infer U> ? U[number] | null : never;
export type ExtractValues<C extends ContextSchema> = {
	[K in keyof C]: ExtractValue<C[K]>;
};
export type UpdateValues<T> = {
	[K in keyof T]?: T[K];
};
/**
 * Тип для обновления значений в контексте
 * @template C - Схема контекста
 * @param values - Значения для обновления
 * @returns Значения, которые были обновлены
 *
 * @includeExample ./context/test/context.basic.spec.ts
 * @includeExample ./context/test/context.types.spec.ts
 */
export type Update<C extends ContextSchema> = (values: UpdateValues<ExtractValues<C>>) => Partial<ExtractValues<C>>;
/**
 * # Условия для булевых значений (required)
  
   Позволяет определять условия для обязательных булевых значений в контексте.
   Не поддерживает проверку на null, так как required поля всегда имеют значение.
  
   ## Параметры:
   | Параметр   | Тип     | Описание                           |
   | ---------- | ------- | ---------------------------------- |
   | eq         | boolean | Равно указанному булеву значению   |
   | notEq      | boolean | Не равно указанному булеву значению|
   | logicalEq  | boolean | Логическое равенство               |
   
   @includeExample ./state/test/conditions.boolean.spec.ts
   */
export type CondBooleanRequired = boolean | {
	/** Равно указанному булеву значению */
	eq?: boolean;
	/** Не равно указанному булеву значению */
	notEq?: boolean;
	/** Логическое равенство */
	logicalEq?: boolean;
};
/**
 * # Условия для булевых значений (optional)
  
   Позволяет определять условия для опциональных булевых значений в контексте.
   Поддерживает проверку на null.
  
   ## Параметры:
   | Параметр   | Тип     | Описание                           |
   | ---------- | ------- | ---------------------------------- |
   | null       | boolean | Является ли значение null          |
   | eq         | boolean | Равно указанному булеву значению   |
   | notEq      | boolean | Не равно указанному булеву значению|
   | logicalEq  | boolean | Логическое равенство               |
   
   @example
   ```typescript
   // Простое условие
   isActive: true
   
   // Проверка на null
   isVerified: null
   
   // Сложное условие
   isAdmin: { eq: true }
   isVerified: { null: true }
   ```
   */
export type CondBooleanOptional = boolean | null | {
	/** Является ли значение null */
	null?: boolean;
	/** Равно указанному булеву значению */
	eq?: boolean;
	/** Не равно указанному булеву значению */
	notEq?: boolean;
	/** Логическое равенство */
	logicalEq?: boolean;
};
/**
 * # Условия для строковых значений (required)
  
   Позволяет определять условия для обязательных строковых значений в контексте.
   Не поддерживает проверку на null, так как required поля всегда имеют значение.
  
   ## Параметры:
   | Параметр      | Тип     | Описание                           |
   | ------------- | ------- | ---------------------------------- |
   | startsWith    | string  | Начинается ли с указанной строки   |
   | endsWith      | string  | Заканчивается ли на указанную строку|
   | include       | string  | Включает ли указанную подстроку    |
   | pattern       | RegExp  | Шаблон регулярного выражения      |
   | eq            | string  | Равно указанной строке             |
   | notEq         | string  | Не равно указанной строке          |
   | notInclude    | string  | Не включает указанную подстроку    |
   | notStartsWith | string  | Не начинается с указанной строки   |
   | notEndsWith   | string  | Не заканчивается на указанную строку|
   | length        | number \| { min?: number; max?: number } | Длина строки |
   | between       | [string, string] | Должно быть между двумя строками |
   
   @includeExample ./state/test/conditions.string.spec.ts
   */
export type CondStringRequired = string | RegExp | {
	/** Начинается ли с указанной строки */
	startsWith?: string;
	/** Заканчивается ли на указанную строку */
	endsWith?: string;
	/** Включает ли указанную подстроку */
	include?: string;
	/** Шаблон регулярного выражения */
	pattern?: RegExp;
	/** Равно указанной строке */
	eq?: string;
	/** Не равно указанной строке */
	notEq?: string;
	/** Не включает указанную подстроку */
	notInclude?: string;
	/** Не начинается с указанной строки */
	notStartsWith?: string;
	/** Не заканчивается на указанную строку */
	notEndsWith?: string;
	/** Длина строки */
	length?: number | {
		min?: number;
		max?: number;
	};
	/** Должно быть между двумя строками */
	between?: [
		string,
		string
	];
};
/**
 * # Условия для строковых значений (optional)
  
   Позволяет определять условия для опциональных строковых значений в контексте.
   Поддерживает проверку на null.
  
   ## Параметры:
   | Параметр      | Тип     | Описание                           |
   | ------------- | ------- | ---------------------------------- |
   | null          | boolean | Является ли значение null          |
   | startsWith    | string  | Начинается ли с указанной строки   |
   | endsWith      | string  | Заканчивается ли на указанную строку|
   | include       | string  | Включает ли указанную подстроку    |
   | pattern       | RegExp  | Шаблон регулярного выражения      |
   | eq            | string  | Равно указанной строке             |
   | notEq         | string  | Не равно указанной строке          |
   | notInclude    | string  | Не включает указанную подстроку    |
   | notStartsWith | string  | Не начинается с указанной строки   |
   | notEndsWith   | string  | Не заканчивается на указанную строку|
   | length        | number \| { min?: number; max?: number } | Длина строки |
   | between       | [string, string] | Должно быть между двумя строками |
   
   @example
   ```typescript
   // Простое условие
   name: 'John'
   
   // Проверка на null
   name: null
   
   // Регулярное выражение
   email: /@/
   
   // Сложное условие
   name: { length: { min: 2 } }
   email: { pattern: /@/, include: '.com' }
   ```
   */
export type CondStringOptional = string | RegExp | null | {
	/** Является ли значение null */
	null?: boolean;
	/** Начинается ли с указанной строки */
	startsWith?: string;
	/** Заканчивается ли на указанную строку */
	endsWith?: string;
	/** Включает ли указанную подстроку */
	include?: string;
	/** Шаблон регулярного выражения */
	pattern?: RegExp;
	/** Равно указанной строке */
	eq?: string;
	/** Не равно указанной строке */
	notEq?: string;
	/** Не включает указанную подстроку */
	notInclude?: string;
	/** Не начинается с указанной строки */
	notStartsWith?: string;
	/** Не заканчивается на указанную строку */
	notEndsWith?: string;
	/** Длина строки */
	length?: number | {
		min?: number;
		max?: number;
	};
	/** Должно быть между двумя строками */
	between?: [
		string,
		string
	];
};
/**
 * # Условия для числовых значений (required)
  
   Позволяет определять условия для обязательных числовых значений в контексте.
   Не поддерживает проверку на null, так как required поля всегда имеют значение.
  
   ## Параметры:
   | Параметр   | Тип     | Описание                           |
   | ---------- | ------- | ---------------------------------- |
   | eq         | number  | Равно указанному числу             |
   | gt         | number  | Больше указанного числа            |
   | gte        | number  | Больше или равно указанному числу  |
   | lt         | number  | Меньше указанного числа            |
   | lte        | number  | Меньше или равно указанному числу  |
   | notEq      | number  | Не равно указанному числу          |
   | notGt      | number  | Не больше указанного числа         |
   | notGte     | number  | Не больше или равно указанному числу|
   | notLt      | number  | Не меньше указанного числа         |
   | notLte     | number  | Не меньше или равно указанному числу|
   | between    | [number, number] | Должно быть между двумя числами |
   
   @includeExample ./state/test/conditions.number.spec.ts
   */
export type CondNumberRequired = number | {
	/** Равно указанному числу */
	eq?: number;
	/** Больше указанного числа */
	gt?: number;
	/** Больше или равно указанному числу */
	gte?: number;
	/** Меньше указанного числа */
	lt?: number;
	/** Меньше или равно указанному числу */
	lte?: number;
	/** Не равно указанному числу */
	notEq?: number;
	/** Не больше указанного числа */
	notGt?: number;
	/** Не больше или равно указанному числу */
	notGte?: number;
	/** Не меньше указанного числа */
	notLt?: number;
	/** Не меньше или равно указанному числу */
	notLte?: number;
	/** Должно быть между двумя числами */
	between?: [
		number,
		number
	];
};
/**
 * # Условия для числовых значений (optional)
  
   Позволяет определять условия для опциональных числовых значений в контексте.
   Поддерживает проверку на null.
  
   ## Параметры:
   | Параметр   | Тип     | Описание                           |
   | ---------- | ------- | ---------------------------------- |
   | null       | boolean | Является ли значение null          |
   | eq         | number  | Равно указанному числу             |
   | gt         | number  | Больше указанного числа            |
   | gte        | number  | Больше или равно указанному числу  |
   | lt         | number  | Меньше указанного числа            |
   | lte        | number  | Меньше или равно указанному числу  |
   | notEq      | number  | Не равно указанному числу          |
   | notGt      | number  | Не больше указанного числа         |
   | notGte     | number  | Не больше или равно указанному числу|
   | notLt      | number  | Не меньше указанного числа         |
   | notLte     | number  | Не меньше или равно указанному числу|
   | between    | [number, number] | Должно быть между двумя числами |
   
   @example
   ```typescript
   // Простое условие
   age: 18
   
   // Проверка на null
   age: null
   
   // Сложное условие
   age: { gte: 18, lte: 65 }
   score: { between: [0, 100] }
   ```
   */
export type CondNumberOptional = number | null | {
	/** Является ли значение null */
	null?: boolean;
	/** Равно указанному числу */
	eq?: number;
	/** Больше указанного числа */
	gt?: number;
	/** Больше или равно указанному числу */
	gte?: number;
	/** Меньше указанного числа */
	lt?: number;
	/** Меньше или равно указанному числу */
	lte?: number;
	/** Не равно указанному числу */
	notEq?: number;
	/** Не больше указанного числа */
	notGt?: number;
	/** Не больше или равно указанному числу */
	notGte?: number;
	/** Не меньше указанного числа */
	notLt?: number;
	/** Не меньше или равно указанному числу */
	notLte?: number;
	/** Должно быть между двумя числами */
	between?: [
		number,
		number
	];
};
/**
 * # Условия для массивов (required)
  
   Позволяет определять условия для обязательных массивов в контексте.
   Не поддерживает проверку на null, так как required поля всегда имеют значение.
  
   ## Параметры:
   | Параметр    | Тип     | Описание                           |
   | ----------- | ------- | ---------------------------------- |
   | length      | number \| { min?: number; max?: number } | Длина массива |
   | includes    | T       | Содержит ли массив указанный элемент |
   | notIncludes | T       | Не содержит ли массив указанный элемент |
   | every       | Condition | Все элементы удовлетворяют условию |
   | some        | Condition | Хотя бы один элемент удовлетворяет условию |
   | isEmpty     | boolean | Является ли массив пустым          |
   
   @example
   ```typescript
   // Простое условие
   tags: ['admin', 'user']
   
   // Сложное условие
   tags: { length: { min: 1 } }
   scores: { every: { gte: 0 } }
   ```
   */
export type CondArrayRequired<T = any> = T[] | {
	/** Длина массива */
	length?: number | {
		min?: number;
		max?: number;
	};
	/** Содержит ли массив указанный элемент */
	includes?: T;
	/** Не содержит ли массив указанный элемент */
	notIncludes?: T;
	/** Все элементы удовлетворяют условию */
	every?: T extends number ? {
		gt?: number;
		gte?: number;
		lt?: number;
		lte?: number;
		eq?: number;
	} : T extends string ? {
		include?: string;
		startsWith?: string;
		endsWith?: string;
		pattern?: RegExp;
	} : never;
	/** Хотя бы один элемент удовлетворяет условию */
	some?: T extends number ? {
		gt?: number;
		gte?: number;
		lt?: number;
		lte?: number;
		eq?: number;
	} : T extends string ? {
		include?: string;
		startsWith?: string;
		endsWith?: string;
		pattern?: RegExp;
	} : never;
	/** Является ли массив пустым */
	isEmpty?: boolean;
};
/**
 * # Условия для массивов (optional)
  
   Позволяет определять условия для опциональных массивов в контексте.
   Поддерживает проверку на null.
  
   ## Параметры:
   | Параметр    | Тип     | Описание                           |
   | ----------- | ------- | ---------------------------------- |
   | null        | boolean | Является ли значение null          |
   | length      | number \| { min?: number; max?: number } | Длина массива |
   | includes    | T       | Содержит ли массив указанный элемент |
   | notIncludes | T       | Не содержит ли массив указанный элемент |
   | every       | Condition | Все элементы удовлетворяют условию |
   | some        | Condition | Хотя бы один элемент удовлетворяет условию |
   | isEmpty     | boolean | Является ли массив пустым          |
   
   @example
   ```typescript
   // Простое условие
   tags: ['admin', 'user']
   
   // Проверка на null
   tags: null
   
   // Сложное условие
   tags: { length: { min: 1 } }
   scores: { every: { gte: 0 } }
   ```
   */
export type CondArrayOptional<T = any> = T[] | null | {
	/** Является ли значение null */
	null?: boolean;
	/** Длина массива */
	length?: number | {
		min?: number;
		max?: number;
	};
	/** Содержит ли массив указанный элемент */
	includes?: T;
	/** Не содержит ли массив указанный элемент */
	notIncludes?: T;
	/** Все элементы удовлетворяют условию */
	every?: T extends number ? {
		gt?: number;
		gte?: number;
		lt?: number;
		lte?: number;
		eq?: number;
	} : T extends string ? {
		include?: string;
		startsWith?: string;
		endsWith?: string;
		pattern?: RegExp;
	} : never;
	/** Хотя бы один элемент удовлетворяет условию */
	some?: T extends number ? {
		gt?: number;
		gte?: number;
		lt?: number;
		lte?: number;
		eq?: number;
	} : T extends string ? {
		include?: string;
		startsWith?: string;
		endsWith?: string;
		pattern?: RegExp;
	} : never;
	/** Является ли массив пустым */
	isEmpty?: boolean;
};
/**
 * Условие для обязательного поля контекста
 */
export type Condition<T> = T extends boolean ? CondBooleanRequired : T extends string ? CondStringRequired : T extends number ? CondNumberRequired : T extends (infer U)[] ? CondArrayRequired<U> : T extends readonly (infer U)[] ? CondArrayRequired<U> : T extends null ? null : never;
/**
 * Условие для опционального поля контекста
 */
export type ConditionOptional<T> = T extends boolean ? CondBooleanOptional : T extends string ? CondStringOptional : T extends number ? CondNumberOptional : T extends (infer U)[] ? CondArrayOptional<U> : T extends readonly (infer U)[] ? CondArrayOptional<U> : T extends null ? null : never;
/**
 * Условия переходов для всех полей контекста
 */
export type TransitionConditions<T extends ContextSchema> = {
	[K in keyof T]?: T[K] extends RequiredStringDefinition | RequiredNumberDefinition | RequiredBooleanDefinition | RequiredArrayDefinition<any> | RequiredEnumDefinition<any> ? Condition<ExtractValues<T>[K]> : ConditionOptional<ExtractValues<T>[K]>;
};
/**
 * Переходы из одного состояния в другие
 */
export type StateTransitions<T extends string, C extends ContextSchema> = {
	[K in T]?: TransitionConditions<C>;
};
/**
 * Определение состояния с возможными переходами
 */
export type StateDefinition<T extends string, C extends ContextSchema> = StateTransitions<T, C>;
/**
 * Конфигурация всех состояний системы
 *
 * @includeExample ./state/test/states.config.basic.spec.ts
 * @includeExample ./state/test/states.config.order.spec.ts
 * @includeExample ./state/test/states.config.numeric.spec.ts
 * @includeExample ./state/test/states.config.multiple.spec.ts
 */
export type StatesConfig<S extends string, C extends ContextSchema> = Record<S, StateDefinition<S, C>>;
/**
 * Тип билдера для декларации набора процессов автомата.
 *
 * Позволяет создавать типизированные процессы с удобным API.
 *
 * @template C - схема контекста автомата
 * @template S - строковые ключи состояний/процессов
 * @param process - фабрика для создания цепочки ProcessChain
 * @returns объект, где ключи — имена процессов, а значения — цепочки ActionChain
 *
 * @includeExample ./proc/test/actions.basic.spec.ts
 * @includeExample ./proc/test/actions.types.spec.ts
 */
export type ActionsDeclaration<C extends ContextSchema, S extends string> = (process: (config?: {
	title?: string;
	description?: string;
}) => ProcessChain<C>) => Partial<Record<S, ActionChain<C, any>>>;
/**
 * Chain API для создания процесса с опциональными параметрами title и description.
 * Позволяет удобно и строго типизировано описывать обработчики процессов автомата.
 *
 * @template C - схема контекста автомата
 * @template Res - возвращаемый тип результата action
 *
 * @example
 * ```typescript
 * const chain = process({
 *   title: "my_process",
 *   description: "Описание процесса"
 * })
 *   .action(({ context }) => ({ name: context.name }))
 *   .success(({ update, data }) => update({ name: data.name }))
 *   .error(({ update, error }) => update({ name: error.message }))
 *
 * chain.getResult() // { action, success, error, title?, description? }
 * ```
 */
export type ProcessChain<C extends ContextSchema> = {
	/**
	 * Добавляет основную функцию процесса.
	 *
	 * Функция может быть как синхронной, так и асинхронной.
	 * При выбросе исключения вызывается обработчик error.
	 * При успешном выполнении вызывается обработчик success.
	 *
	 * @param fn - функция процесса, вызываемая автоматом
	 * @returns цепочку для дальнейшего конфигурирования
	 *
	 * @example
	 * ```typescript
	 * // Синхронная функция
	 * .action(({ context }) => {
	 *   if (!context.email) {
	 *     throw new Error('Email обязателен')
	 *   }
	 *   return { isValid: true }
	 * })
	 *
	 * // Асинхронная функция
	 * .action(async ({ context }) => {
	 *   const response = await fetch('/api/data', {
	 *     method: 'POST',
	 *     body: JSON.stringify(context)
	 *   })
	 *   return await response.json()
	 * })
	 * ```
	 */
	action: <Res>(fn: (params: {
		context: ExtractValues<C>;
	}) => Res | Promise<Res>) => ActionChain<C, Res>;
};
/**
 * Цепочка для декларации action с типобезопасной поддержкой success и error.
 * Позволяет удобно и строго типизировано описывать обработчики процессов автомата.
 *
 * @template C - схема контекста автомата
 * @template Res - возвращаемый тип результата action
 *
 * @example
 * ```typescript
 * const chain = action(({ context }) => ({ name: context.name }))
 *   .success(({ update, data }) => update({ name: data.name }))
 *   .error(({ update, error }) => update({ name: error.message }))
 *
 * chain.getResult() // { action, success, error }
 * ```
 */
export type ActionChain<C extends ContextSchema, Res> = {
	/**
	 * Основная функция процесса, вызывается автоматом.
	 *
	 * Получает текущий контекст и должна вернуть результат или выбросить исключение.
	 *
	 * @param params - объект с текущим контекстом
	 * @returns результат процесса (может быть промисом)
	 *
	 * @example
	 * ```typescript
	 * action: ({ context }) => {
	 *   // Доступ к контексту
	 *   console.log(context.email, context.password)
	 *
	 *   // Возврат результата
	 *   return { userId: 123, token: "abc" }
	 * }
	 * ```
	 */
	action: (params: {
		context: ExtractValues<C>;
	}) => Res | Promise<Res>;
	/**
	 * Добавляет обработчик успешного завершения процесса.
	 *
	 * Вызывается когда action завершился успешно (не выбросил исключение).
	 * Получает функцию update для изменения контекста и данные от action.
	 *
	 * @param handler - функция, вызываемая при успехе (получает update и data)
	 * @returns цепочку для дальнейшего конфигурирования
	 *
	 * @example
	 * ```typescript
	 * .success(({ update, data }) => {
	 *   // Обновляем контекст данными от action
	 *   update({
	 *     userId: data.userId,
	 *     token: data.token,
	 *     isAuthenticated: true,
	 *     error: ""
	 *   })
	 * })
	 * ```
	 */
	success: (handler: (params: {
		update: (values: Partial<ExtractValues<C>>) => void;
		data: Res;
	}) => void) => ActionChain<C, Res>;
	/**
	 * Добавляет обработчик ошибки выполнения процесса.
	 *
	 * Вызывается когда action выбросил исключение.
	 * Получает функцию update для изменения контекста и объект ошибки.
	 *
	 * @param handler - функция, вызываемая при ошибке (получает update и error типа Error)
	 * @returns цепочку для дальнейшего конфигурирования
	 *
	 * @example
	 * ```typescript
	 * .error(({ update, error }) => {
	 *   // Обрабатываем ошибку
	 *   update({
	 *     error: error.message,
	 *     isAuthenticated: false,
	 *     isLoading: false
	 *   })
	 * })
	 * ```
	 */
	error: (handler: (params: {
		update: (values: Partial<ExtractValues<C>>) => void;
		error: Error;
	}) => void) => ActionChain<C, Res>;
	/**
	 * Возвращает итоговый объект конфигурации процесса для автомата.
	 *
	 * Содержит все обработчики и метаданные процесса.
	 *
	 * @returns объект с action, success, error, title и description (если заданы)
	 *
	 * @example
	 * ```typescript
	 * const processConfig = chain.getResult()
	 * // {
	 * //   action: Function,
	 * //   success: Function,
	 * //   error: Function,
	 * //   title: "Авторизация",
	 * //   description: "Процесс входа пользователя"
	 * // }
	 * ```
	 */
	getResult: () => Process<C, Res>;
};
/**
 * Конфигурация одного процесса
 *
 * Содержит основную функцию action и опциональные обработчики success/error.
 * Также может содержать метаданные title и description.
 *
 * @template C - схема контекста автомата
 * @template Res - возвращаемый тип результата action
 *
 * @example
 * ```typescript
 * const process: Process<MyContext, { userId: number }> = {
 *   title: "Авторизация",
 *   description: "Процесс входа пользователя",
 *   action: async ({ context }) => {
 *     // Логика авторизации
 *     return { userId: 123 }
 *   },
 *   success: ({ update, data }) => {
 *     update({ userId: data.userId, isAuthenticated: true })
 *   },
 *   error: ({ update, error }) => {
 *     update({ error: error.message })
 *   }
 * }
 * ```
 */
export type Process<C extends ContextSchema, Res = any> = {
	/** Основная функция процесса */
	action: (params: {
		context: ExtractValues<C>;
	}) => Res | Promise<Res>;
	/** Обработчик успешного завершения */
	success?: (params: {
		update: (values: UpdateValues<ExtractValues<C>>) => void;
		data: Res;
	}) => void;
	/** Обработчик ошибки */
	error?: (params: {
		update: (values: UpdateValues<ExtractValues<C>>) => void;
		error: Error;
	}) => void;
	/** Название процесса для документации */
	title?: string;
	/** Описание процесса для документации */
	description?: string;
};
declare function map<T>(items: Iterable<T> | undefined, f: (value: T, index: number) => unknown): Generator<unknown, void, unknown>;
export type ResultType = typeof HTML_RESULT | typeof SVG_RESULT | typeof MATHML_RESULT;
declare const HTML_RESULT = 1;
declare const SVG_RESULT = 2;
declare const MATHML_RESULT = 3;
declare const ATTRIBUTE_PART = 1;
declare const PROPERTY_PART = 3;
declare const BOOLEAN_ATTRIBUTE_PART = 4;
declare const EVENT_PART = 5;
/**
 * Результат шаблона до компиляции.
 * Содержит строки и значения для интерполяции.
 *
 * Поддерживает специальный атрибут `context` для передачи данных между компонентами:
 * ```ts
 * html`<metafor-child context=${contextObject}></metafor-child>`
 * ```
 */
export type UncompiledTemplateResult<T extends ResultType = ResultType> = {
	["_$htmlType$"]: T;
	strings: TemplateStringsArray;
	values: unknown[];
};
export type TemplateResult<T extends ResultType = ResultType> = UncompiledTemplateResult<T>;
export type Part = any;
export interface Disconnectable {
	_$parent?: Disconnectable | undefined;
	_$disconnectableChildren?: Set<Disconnectable>;
	_$isConnected: boolean;
}
export interface DirectiveParent {
	_$parent?: DirectiveParent | undefined;
	_$isConnected: boolean;
	__directive?: any;
	__directives?: Array<any | undefined>;
}
export type ValueSanitizer = (value: unknown) => unknown;
export interface RenderOptions {
	host?: object;
	renderBefore?: ChildNode | null;
	creationScope?: {
		importNode(node: Node, deep?: boolean): Node;
	};
	isConnected?: boolean;
}
/**
 * Интерфейс класса-директивы (конструктор).
 */
export interface DirectiveClass {
	new (part: PartInfo): unknown;
}
/**
 * Этот утилитарный тип извлекает сигнатуру метода render() класса директивы,
 * чтобы использовать её для типа генерируемой функции директивы.
 */
export type DirectiveParameters<C extends Directive> = Parameters<C["render"]>;
/**
 * Результат вызова функции-директивы. Не выполняет саму директиву, а только
 * возвращает объект с аргументами для дальнейшей обработки.
 */
export interface DirectiveResult<C extends DirectiveClass = DirectiveClass> {
	/**
	 * Это свойство не должно быть минифицировано.
	 * @internal
	 */
	["_$htmlDirective$"]: C;
	/** @internal */
	values: unknown[];
}
declare const PartType: {
	readonly ATTRIBUTE: 1;
	readonly CHILD: 2;
	readonly PROPERTY: 3;
	readonly BOOLEAN_ATTRIBUTE: 4;
	readonly EVENT: 5;
	readonly ELEMENT: 6;
};
export type PartType = (typeof PartType)[keyof typeof PartType];
/**
 * Информация о части типа CHILD.
 */
export interface ChildPartInfo {
	readonly type: typeof PartType.CHILD;
}
/**
 * Информация о части типа ATTRIBUTE, PROPERTY, BOOLEAN_ATTRIBUTE, EVENT.
 */
export interface AttributePartInfo {
	readonly type: typeof PartType.ATTRIBUTE | typeof PartType.PROPERTY | typeof PartType.BOOLEAN_ATTRIBUTE | typeof PartType.EVENT;
	readonly strings?: ReadonlyArray<string>;
	readonly name: string;
	readonly tagName: string;
}
/**
 * Информация о части типа ELEMENT.
 */
export interface ElementPartInfo {
	readonly type: typeof PartType.ELEMENT;
}
/**
 * Информация о части шаблона, к которой привязана директива.
 *
 * Используется для проверки, что директива применяется к корректной части шаблона.
 */
export type PartInfo = ChildPartInfo | AttributePartInfo | ElementPartInfo;
declare abstract class Directive implements Disconnectable {
	__part: Part;
	__attributeIndex: number | undefined;
	__directive?: Directive;
	_$parent: Disconnectable;
	_$disconnectableChildren?: Set<Disconnectable>;
	["_$notifyDirectiveConnectionChanged"]?(isConnected: boolean): void;
	constructor(_partInfo: PartInfo);
	get _$isConnected(): boolean;
	/** @internal */
	_$initialize(part: Part, parent: Disconnectable, attributeIndex: number | undefined): void;
	/** @internal */
	_$resolve(part: Part, props: Array<unknown>): unknown;
	/**
	 * Метод, который должен быть реализован в пользовательской директиве.
	 * Возвращает значение для вставки в шаблон.
	 */
	abstract render(...props: Array<unknown>): unknown;
	/**
	 * Метод обновления директивы. По умолчанию вызывает render().
	 */
	update(_part: Part, props: Array<unknown>): unknown;
}
declare const html: (strings: TemplateStringsArray, ...values: unknown[]) => TemplateResult<1>;
declare const noChange: unique symbol;
declare class AttributePart implements Disconnectable {
	readonly type: typeof ATTRIBUTE_PART | typeof PROPERTY_PART | typeof BOOLEAN_ATTRIBUTE_PART | typeof EVENT_PART;
	readonly element: HTMLElement;
	readonly name: string;
	readonly options: RenderOptions | undefined;
	/**
	 * Если этот атрибутный часть представляет интерполяцию, это содержит
	 * статические строки интерполяции. Для однозначных связываний это
	 * undefined.
	 */
	readonly strings?: ReadonlyArray<string>;
	/** @internal */
	_$committedValue: unknown | Array<unknown>;
	/** @internal */
	__directives?: Array<Directive | undefined>;
	/** @internal */
	_$parent: Disconnectable;
	/** @internal */
	_$disconnectableChildren?: Set<Disconnectable>;
	protected _sanitizer: ValueSanitizer | undefined;
	get tagName(): string;
	get _$isConnected(): boolean;
	constructor(element: HTMLElement, name: string, strings: ReadonlyArray<string>, parent: Disconnectable, options: RenderOptions | undefined);
	/**
	 * Устанавливает значение этой части, разрешая значение из возможных
	 * значений и статических строк и коммитит его в DOM.
	 * Если эта часть однозначная, `this._strings` будет undefined, и метод
	 * будет вызываться с одним значением аргументом. Если эта часть
	 * многозначная, метод вызывается с массивом значений части, и
	 * смещением в массив значений, с которого должны читаться значения.
	 * Этот метод перегружен таким образом, чтобы избежать временных срезов
	 * значений экземпляра шаблона в массиве, и позволить быстрому пути для
	 * однозначных частей.
	 *
	 * @param value Значение части, или массив значений для многозначных частей
	 * @param valueIndex индекс для чтения значений. `undefined` для
	 *   однозначных частей
	 * @param noCommit вызывает часть, чтобы она не коммитила свое значение в DOM.
	 *   Используется в гидратации для первоначального значения атрибута,
	 *   но не устанавливает атрибут, и в SSR для отключения операции DOM и
	 *   захвата значения для сериализации.
	 *
	 * @internal
	 */
	_$setValue(value: unknown | Array<unknown>, directiveParent?: DirectiveParent, valueIndex?: number, noCommit?: boolean): void;
	/** @internal */
	_commitValue(value: unknown): void;
}
declare class ElementPart implements Disconnectable {
	element: Element;
	readonly type = 6;
	/** @internal */
	__directive?: Directive;
	_$committedValue: undefined;
	/** @internal */
	_$parent: Disconnectable;
	/** @internal */
	_$disconnectableChildren?: Set<Disconnectable>;
	options: RenderOptions | undefined;
	constructor(element: Element, parent: Disconnectable, options: RenderOptions | undefined);
	get _$isConnected(): boolean;
	_$setValue(value: unknown): void;
}
declare abstract class AsyncDirective extends Directive {
	/**
	 * Состояние соединения для этой директивы.
	 */
	isConnected: boolean;
	_$disconnectableChildren?: Set<Disconnectable>;
	/**
	 * Инициализирует часть внутренними полями
	 * @param part
	 * @param parent
	 * @param attributeIndex
	 */
	_$initialize(part: Part, parent: Disconnectable, attributeIndex: number | undefined): void;
	/**
	 * Вызывается из основного кода, когда директива уходит от части (в этом случае
	 * `shouldRemoveFromParent` должно быть true), и из вспомогательной функции
	 * `setChildrenConnected` при рекурсивном изменении состояния соединения дерева (в
	 * этом случае `shouldRemoveFromParent` должно быть false).
	 *
	 * @param isConnected
	 * @param isClearingDirective - True, когда директива сама удаляется; false, когда
	 *     дерево отключается
	 * @internal
	 */
	["_$notifyDirectiveConnectionChanged"](isConnected: boolean, isClearingDirective?: boolean): void;
	/**
	 * Устанавливает значение Part директивы вне обычного жизненного цикла директивы.
	 *
	 * Этот метод не должен вызываться синхронно из `update`
	 * или `render` директивы.
	 *
	 * @param value Значение для установки
	 */
	setValue(value: unknown): void;
	/**
	 * Колбэки пользователя для реализации логики освобождения любых ресурсов/подписок,
	 * которые могли быть удержаны этой директивой. Поскольку директивы также могут быть
	 * повторно подключены, `reconnected` также должен быть реализован для восстановления
	 * рабочего состояния директивы перед следующим рендерингом.
	 */
	protected disconnected(): void;
	protected reconnected(): void;
}
declare class Ref<T = Element> {
	/**
	 * Текущее значение элемента ref, либо `undefined`, если ref больше не отрисован.
	 */
	readonly value?: T;
}
export type RefOrCallback<T = Element> = Ref<T> | ((el: T | undefined) => void);
declare class RefDirective extends AsyncDirective {
	private _element?;
	private _ref?;
	private _context?;
	render(_ref?: RefOrCallback): symbol;
	update(part: ElementPart, [ref]: Parameters<this["render"]>): symbol;
	private _updateRefValue;
	private get _lastElementForRef();
	disconnected(): void;
	reconnected(): void;
}
declare const ref: (...values: unknown[]) => DirectiveResult<typeof RefDirective>;
export type KeyFn<T> = (item: T, index: number) => unknown;
export type ItemTemplate<T> = (item: T, index: number) => unknown;
export interface RepeatDirectiveFn {
	<T>(items: Iterable<T>, keyFnOrTemplate: KeyFn<T> | ItemTemplate<T>, template?: ItemTemplate<T>): unknown;
	<T>(items: Iterable<T>, template: ItemTemplate<T>): unknown;
	<T>(items: Iterable<T>, keyFn: KeyFn<T> | ItemTemplate<T>, template: ItemTemplate<T>): unknown;
}
declare const repeat: RepeatDirectiveFn;
/**
 * Набор CSS-свойств и их значений в формате ключ-значение.
 *
 * Ключ должен быть либо строкой с корректным именем CSS-свойства (например, 'background-color'),
 * либо корректным camelCase-именем для CSSStyleDeclaration (например, backgroundColor).
 */
export interface StyleInfo {
	[name: string]: string | number | undefined | null;
}
declare class StyleMapDirective extends Directive {
	private _previousStyleProperties?;
	constructor(partInfo: PartInfo);
	render(styleInfo: Readonly<StyleInfo>): string;
	update(part: AttributePart, [styleInfo]: DirectiveParameters<this>): string | typeof noChange;
}
declare const styleMap: (...values: unknown[]) => DirectiveResult<typeof StyleMapDirective>;
/**
 * Директива when
 * @module HTML
 */
export type Falsy = null | undefined | false | 0 | -0 | 0n | "";
declare function when<C extends Falsy, T, F = undefined>(condition: C, trueCase: (c: C) => T, falseCase?: (c: C) => F): F;
declare function when<C, T, F>(condition: C extends Falsy ? never : C, trueCase: (c: C) => T, falseCase?: (c: C) => F): T;
declare function when<C, T, F = undefined>(condition: C, trueCase: (c: Exclude<C, Falsy>) => T, falseCase?: (c: Extract<C, Falsy>) => F): C extends Falsy ? F : T;
/**
 * Параметры функции рендеринга представления актора.
 *
 * В функцию render компонента MetaFor передаётся объект с полезными утилитами и данными для построения UI.
 *
 * @includeExample ./test/context.init.spec.ts
 * @includeExample ./test/context.update.spec.ts
 *
 * @example
 * ```ts
 * render({ context, update, state, html, ref, repeat, when, map, style }) {
 *   const inputRef = ref();
 *   return html`
 *     <div ${style({ color: state === 'error' ? 'red' : 'black' })}>
 *       <h2>${context.title}</h2>
 *       <input ${ref(inputRef)} value=${context.value} @input=${e => update({ value: e.target.value })} />
 *       <ul>
 *         ${repeat(context.items, (item, i) => html`<li>${i}: ${item}</li>`)}
 *       </ul>
 *       ${when(context.items.length > 0, () => html`<span>Есть элементы</span>`, () => html`<span>Пусто</span>`)}
 *       <ol>
 *         ${map(context.items, (item, i) => html`<li>${item}</li>`)}
 *       </ol>
 *     </div>
 *   `;
 * }
 * ```
 */
export type ViewDefinitionParams<C extends ContextSchema, S extends string> = {
	/**
	 * Функция для обновления контекста.
	 * Вызывается с частичным объектом контекста для изменения состояния.
	 * @example
	 * ```ts
	 * update({ value: 42 })
	 * ```
	 */
	update: Update<C>;
	/**
	 * Текущее состояние контекста.
	 * Содержит все поля, определённые в .context(...)
	 * @example
	 * ```ts
	 * html`<div>${context.value}</div>`
	 * ```
	 */
	context: ExtractValues<C>;
	/**
	 * Текущее состояние автомата/актора.
	 * Обычно строка, определённая в .states(...)
	 * @example
	 * ```ts
	 * html`<span>${state === 'error' ? 'Ошибка' : 'Ок'}</span>`
	 * ```
	 */
	state: S;
	/**
	 * Функция шаблонизации (аналог lit-html).
	 * Используется для создания HTML-шаблонов с интерполяцией.
	 * @example
	 * ```ts
	 * html`<div>${context.value}</div>`
	 * ```
	 */
	html: typeof html;
	/**
	 * Директива для получения ссылки на DOM-элемент.
	 * Используется для доступа к элементу после рендера.
	 * @example
	 * ```ts
	 * const r = ref();
	 * html`<input ${ref(r)} />`
	 * // r.value будет содержать DOM-элемент
	 * ```
	 */
	ref: typeof ref;
	/**
	 * Директива для эффективного рендера списков с ключами.
	 * Позволяет оптимально обновлять DOM при изменении массива.
	 * @example
	 * ```ts
	 * html`<ul>${repeat(context.items, (item, i) => html`<li>${i}: ${item}</li>`)}</ul>`
	 * ```
	 *
	 * Или возвращать напрямую:
	 * ```ts
	 * return repeat(context.items, (item, i) => html`<li>${i}: ${item}</li>`)
	 * ```
	 */
	repeat: typeof repeat;
	/**
	 * Директива для условного рендера.
	 * Позволяет элегантно отображать разные шаблоны в зависимости от условия.
	 * @example
	 * ```ts
	 * html`<div>${when(flag, () => html`<span>Да</span>`, () => html`<span>Нет</span>`)}</div>`
	 * ```
	 *
	 * Или возвращать напрямую:
	 * ```ts
	 * return when(flag, () => html`<span>Да</span>`, () => html`<span>Нет</span>`)
	 * ```
	 */
	when: typeof when;
	/**
	 * Директива для простого отображения массива в элементы.
	 * Удобна для простых случаев, когда не нужны ключи.
	 * @example
	 * ```ts
	 * html`<ul>${map(items, (item, i) => html`<li>${item}</li>`)}</ul>`
	 * ```
	 *
	 * Или возвращать напрямую:
	 * ```ts
	 * return map(items, (item, i) => html`<li>${item}</li>`)
	 * ```
	 */
	map: typeof map;
	/**
	 * Директива для применения inline-стилей к элементу.
	 * Позволяет динамически задавать стили через объект.
	 * @example
	 * ```ts
	 * html`<div ${style({ color: 'red', fontWeight: 600 })}></div>`
	 * ```
	 */
	style: typeof styleMap;
};
/**
 * Конфигурация для представления компонента.
 *
 * Поддерживает передачу контекста между компонентами через атрибут `context`.
 * При первой отрисовке контекст устанавливается без дополнительных сообщений,
 * при обновлении контекста родителя автоматически обновляется контекст ребенка.
 *
 * @includeExample ./test/context.init.spec.ts
 * @includeExample ./test/context.update.spec.ts
 */
export interface ViewConfig<C extends ContextSchema, S extends string> {
	/**
	 * Функция рендеринга компонента.
	 * Получает параметры с контекстом, состоянием и утилитами для построения UI.
	 *
	 * Поддерживает передачу контекста дочерним компонентам через атрибут `context`:
	 * ```ts
	 * render: ({ context, html }) => html`
	 *   <div>
	 *     <h1>Родитель: ${context.parentMessage}</h1>
	 *     <metafor-child
	 *       context=${{
	 *         message: context.parentMessage,
	 *         count: context.parentCount,
	 *       }}></metafor-child>
	 *   </div>
	 * `
	 * ```
	 */
	render?: (params: ViewDefinitionParams<C, S>) => TemplateResult;
	/**
	 * Функция, вызываемая после монтирования компонента в DOM.
	 * Используется для инициализации после рендера.
	 */
	onMount?: (...args: unknown[]) => unknown;
	/**
	 * Функция, вызываемая при уничтожении компонента.
	 * Используется для очистки ресурсов.
	 */
	onDestroy?: (...args: unknown[]) => unknown;
	/**
	 * Функция для определения CSS-стилей компонента.
	 * Получает функцию css для создания инкапсулированных стилей.
	 */
	style?: ({ css }: {
		css: (strings: TemplateStringsArray, ...values: any[]) => CSSStyleSheet;
	}) => void;
}
/**
Метаданные сообщения

@property tag - Имя типа актора (компонента)
@property timestamp - Время отправки сообщения в миллисекундах
*/
export type MetaDataMessage = {
	tag: string;
	index?: number;
	timestamp?: number;
};
export type JsonPatch = {
	op: "replace" | "add" | "remove" | "test";
	path: "/context" | "/state" | "/";
	value?: any;
};
/**
 * Аргументы для функции фильтрации
 *
 * Содержит метаданные сообщения и патч для проверки условий фильтра.
 *
 * @includeExample ./react/test/reactions.basic.spec.ts
 * @includeExample ./react/test/reactions.execution.spec.ts
 */
export type ReactionFilterArgs = {
	/** Метаданные сообщения (тег, индекс, временная метка) */
	meta: MetaDataMessage;
	/** JSON Patch с операцией, путем и значением */
	patch: JsonPatch;
};
/**
 * Функция обновления контекста
 *
 * Вызывается когда реакция срабатывает и фильтр прошел успешно.
 * Получает все необходимые данные для обработки события.
 *
 * @template C - схема контекста
 * @template S - строковые ключи состояний
 * @template Core - тип core объекта
 *
 * @includeExample ./react/test/reactions.basic.spec.ts
 * @includeExample ./react/test/reactions.execution.spec.ts
 *
 * @example
 * ```typescript
 * const updateFn: ReactionUpdate<MyContext, "idle" | "loading"> = ({
 *   update,    // Функция для обновления контекста
 *   context,   // Текущий контекст
 *   core,      // Core объект
 *   meta,      // Метаданные сообщения
 *   patch,     // JSON Patch
 *   state      // Текущее состояние
 * }) => {
 *   // Обработка события
 *   update({
 *     lastMessage: patch.value,
 *     messageCount: context.messageCount + 1
 *   })
 * }
 * ```
 */
export type ReactionUpdate<C extends ContextSchema, S extends string, Core = Record<string, any>> = (args: {
	/** Функция для обновления контекста */
	update: (values: Partial<ExtractValues<C>>) => void;
	/** Текущий контекст */
	context: ExtractValues<C>;
	/** Core объект */
	core: Core;
	/** Метаданные сообщения */
	meta: MetaDataMessage;
	/** JSON Patch */
	patch: JsonPatch;
	/** Текущее состояние */
	state: S;
}) => void;
/**
 * Декларативные условия фильтрации реакций
 *
 * Плоская структура с расширенными возможностями для meta и patch.
 * Позволяет фильтровать события по различным критериям.
 *
 * @example
 * ```typescript
 * const conditions: ReactionFilterConditions = {
 *   tag: "user",                    // Фильтр по тегу
 *   op: "replace",                  // Фильтр по операции
 *   path: "/context",               // Фильтр по пути
 *   value: { gt: 0 },               // Фильтр по значению
 *   index: { gte: 0 },              // Фильтр по индексу
 *   timestamp: { gt: Date.now() }   // Фильтр по временной метке
 * }
 * ```
 */
export type ReactionFilterConditions = {
	/**
	 # Фильтрация по тегу
	 
	 1. Прямое сравнение строки с условием
	  - tag: "test" - тег должен быть равен "test"
	  - tag: /test/ - тег должен соответствовать регулярному выражению /test/ (без кавычек)
	 
	 2. Сравнение с условием
	  - tag: { eq: "test" } - тег должен быть равен "test"
	  - tag: { pattern: /test/ } - тег должен соответствовать регулярному выражению /test/
  
	 Условия сравнения:
	 | Параметр       | Тип                                  | Описание                              |
	 | -------------- | ------------------------------------ | ------------------------------------- |
	 | startsWith     | string                               | Начинается ли с указанной строки      |
	 | endsWith       | string                               | Заканчивается ли на указанную строку  |
	 | include        | string                               | Включает ли указанную подстроку       |
	 | pattern        | RegExp                               | Шаблон регулярного выражения          |
	 | eq             | string                               | Равно указанной строке                |
	 | notEq          | string                               | Не равно указанной строке             |
	 | notInclude     | string                               | Не включает указанную подстроку       |
	 | notStartsWith  | string                               | Не начинается с указанной строки      |
	 | notEndsWith    | string                               | Не заканчивается на указанную строку  |
	 | length         | number \| { min?: number; max?: number } | Длина строки                      |
	 | between        | [string, string]                     | Должно быть между двумя строками      |
	 
	 @example
	 ```typescript
	 // Простые фильтры
	 tag: "user"
	 tag: /^user_/
	 
	 // Сложные фильтры
	 tag: {
	   startsWith: "user",
	   notInclude: "admin"
	 }
	 tag: {
	   pattern: /^[a-z]+_[0-9]+$/,
	   length: { min: 3, max: 20 }
	 }
	 ```
	*/
	tag?: CondStringRequired;
	/**
	 # Фильтрация по индексу
	 
	 1. Прямое сравнение числа с условием
	  - index: 5 - индекс должен быть равен 5
	 
	 2. Сравнение с условием
	  - index: { eq: 5 } - индекс должен быть равен 5
	  - index: { gt: 3 } - индекс должен быть больше 3
  
	 Условия сравнения:
	 | Параметр       | Тип                                  | Описание                              |
	 | -------------- | ------------------------------------ | ------------------------------------- |
	 | eq             | number                               | Равно указанному числу                |
	 | notEq          | number                               | Не равно указанному числу             |
	 | gt             | number                               | Больше указанного числа               |
	 | gte            | number                               | Больше или равно указанному числу     |
	 | lt             | number                               | Меньше указанного числа               |
	 | lte            | number                               | Меньше или равно указанному числу     |
	 | notGt          | number                               | Не больше указанного числа            |
	 | notGte         | number                               | Не больше или равно указанному числу  |
	 | notLt          | number                               | Не меньше указанного числа            |
	 | notLte         | number                               | Не меньше или равно указанному числу  |
	 | between        | [number, number]                     | Должно быть между двумя числами       |
	 
	 @example
	 ```typescript
	 // Простые фильтры
	 index: 0
	 index: { gt: 10 }
	 
	 // Сложные фильтры
	 index: {
	   gte: 0,
	   lte: 100
	 }
	 index: {
	   between: [1, 10],
	   notEq: 5
	 }
	 ```
	*/
	index?: CondNumberRequired;
	/**
	 # Фильтрация по временной метке
	 
	 1. Прямое сравнение числа с условием
	  - timestamp: 1640995200000 - временная метка должна быть равна 1640995200000
	 
	 2. Сравнение с условием
	  - timestamp: { eq: 1640995200000 } - временная метка должна быть равна 1640995200000
	  - timestamp: { gt: 1640995200000 } - временная метка должна быть больше 1640995200000
  
	 Условия сравнения:
	 | Параметр       | Тип                                  | Описание                              |
	 | -------------- | ------------------------------------ | ------------------------------------- |
	 | eq             | number                               | Равно указанному числу                |
	 | notEq          | number                               | Не равно указанному числу             |
	 | gt             | number                               | Больше указанного числа               |
	 | gte            | number                               | Больше или равно указанному числу     |
	 | lt             | number                               | Меньше указанного числа               |
	 | lte            | number                               | Меньше или равно указанному числу     |
	 | notGt          | number                               | Не больше указанного числа            |
	 | notGte         | number                               | Не больше или равно указанному числу  |
	 | notLt          | number                               | Не меньше указанного числа            |
	 | notLte         | number                               | Не меньше или равно указанному числу  |
	 | between        | [number, number]                     | Должно быть между двумя числами       |
	 
	 @example
	 ```typescript
	 // Фильтры по времени
	 timestamp: { gt: Date.now() - 60000 }  // Последняя минута
	 timestamp: {
	   gte: Date.now() - 3600000,           // Последний час
	   lte: Date.now()
	 }
	 ```
	*/
	timestamp?: CondNumberRequired;
	/**
	 # Фильтрация по операции патча
	 
	 Доступные операции:
	 | Операция       | Описание                              |
	 | -------------- | ------------------------------------- |
	 | replace        | Замена значения по указанному пути    |
	 | add            | Добавление нового значения по пути     |
	 | remove         | Удаление значения по указанному пути   |
	 | test           | Проверка значения по указанному пути   |
	 
	 Примеры использования:
	 - op: "replace" - операция должна быть replace
	 - op: "add" - операция должна быть add
	 
	 @example
	 ```typescript
	 // Фильтры по операции
	 op: "replace"  // Только замены
	 op: "add"      // Только добавления
	 op: "remove"   // Только удаления
	 ```
	*/
	op?: "replace" | "add" | "remove" | "test";
	/**
	 # Фильтрация по пути патча
	 
	 Доступные пути:
	 | Путь           | Описание                              |
	 | -------------- | ------------------------------------- |
	 | /context       | Путь к контексту актора               |
	 | /state         | Путь к состоянию актора               |
	 | /              | Корневой путь (полный объект актора)  |
	 
	 Примеры использования:
	 - path: "/context" - путь должен быть /context
	 - path: "/state" - путь должен быть /state
	 
	 @example
	 ```typescript
	 // Фильтры по пути
	 path: "/context"  // Только изменения контекста
	 path: "/state"    // Только изменения состояния
	 path: "/"         // Любые изменения
	 ```
	*/
	path?: "/context" | "/state" | "/";
	/**
	 # Фильтрация по значению патча
	 
	 Поддерживает все типы значений с расширенными условиями сравнения.
	 
	 ## Строковые значения
	 
	 1. Прямое сравнение
	  - value: "active" - значение должно быть равно "active"
	  - value: /test/ - значение должно соответствовать регулярному выражению
	 
	 2. Расширенные условия
	 
	 | Параметр       | Тип                                  | Описание                              |
	 | -------------- | ------------------------------------ | ------------------------------------- |
	 | eq             | string                               | Равно указанной строке                |
	 | notEq          | string                               | Не равно указанной строке             |
	 | startsWith     | string                               | Начинается ли с указанной строки      |
	 | endsWith       | string                               | Заканчивается ли на указанную строку  |
	 | include        | string                               | Включает ли указанную подстроку       |
	 | notInclude     | string                               | Не включает указанную подстроку       |
	 | notStartsWith  | string                               | Не начинается с указанной строки      |
	 | notEndsWith    | string                               | Не заканчивается на указанную строку  |
	 | pattern        | RegExp                               | Шаблон регулярного выражения          |
	 | length         | number \| { min?: number; max?: number } | Длина строки                      |
	 | between        | [string, string]                     | Должно быть между двумя строками      |
	 
	 ## Числовые значения
	 
	 1. Прямое сравнение
	  - value: 42 - значение должно быть равно 42
	 
	 2. Расширенные условия
	 
	 | Параметр | Тип              | Описание                              |
	 | -------- | ---------------- | ------------------------------------- |
	 | eq       | number           | Равно указанному числу                |
	 | notEq    | number           | Не равно указанному числу             |
	 | gt       | number           | Больше указанного числа               |
	 | gte      | number           | Больше или равно указанному числу     |
	 | lt       | number           | Меньше указанного числа               |
	 | lte      | number           | Меньше или равно указанному числу     |
	 | notGt    | number           | Не больше указанного числа            |
	 | notGte   | number           | Не больше или равно указанному числу  |
	 | notLt    | number           | Не меньше указанного числа            |
	 | notLte   | number           | Не меньше или равно указанному числу  |
	 | between  | [number, number] | Должно быть между двумя числами       |
	 
	 ## Булевы значения
	 
	 1. Прямое сравнение
	  - value: true - значение должно быть true
	 
	 2. Расширенные условия
	 
	 | Параметр   | Тип     | Описание                           |
	 | ---------- | ------- | ---------------------------------- |
	 | eq         | boolean | Равно указанному булеву значению   |
	 | notEq      | boolean | Не равно указанному булеву значению|
	 | logicalEq  | boolean | Логическое равенство               |
	 
	 ## Массивы
	 
	 1. Прямое сравнение
	  - value: [1, 2, 3] - массив должен быть равен [1, 2, 3]
	 
	 2. Расширенные условия
	 
	 | Параметр    | Тип              | Описание                              |
	 | ----------- | ---------------- | ------------------------------------- |
	 | length      | number \| { min?: number; max?: number } | Длина массива                    |
	 | includes    | any              | Содержит ли массив указанный элемент  |
	 | notIncludes | any              | Не содержит ли массив указанный элемент|
	 | every       | { gt?: number; gte?: number; lt?: number; lte?: number; eq?: number; include?: string } | Все элементы удовлетворяют условию |
	 | some        | { gt?: number; gte?: number; lt?: number; lte?: number; eq?: number; include?: string } | Хотя бы один элемент удовлетворяет условию |
	 | isEmpty     | boolean          | Является ли массив пустым             |
	 
	 ## Null и undefined
	 
	 | Параметр | Тип     | Описание                    |
	 | -------- | ------- | --------------------------- |
	 | null     | boolean | Является ли значение null   |
	 
	 ## Объекты
	 
	 - value: { name: "test" } - объект должен быть равен { name: "test" }
	 
	 ## Комбинированные условия
	 
	 Можно комбинировать с другими фильтрами:
	 ```typescript
	 filter({
	   value: { gt: 10, lt: 100 },
	   op: "replace",
	   path: "/context"
	 })
	 ```
	 
	 @example
	 ```typescript
	 // Простые фильтры
	 value: "active"
	 value: 42
	 value: true
	 value: [1, 2, 3]
	 
	 // Сложные фильтры
	 value: {
	   gt: 0,
	   lt: 100
	 }
	 value: {
	   startsWith: "user",
	   length: { min: 3 }
	 }
	 value: {
	   includes: "admin",
	   length: { min: 1 }
	 }
	 ```
	*/
	value?: Condition<any> | ConditionOptional<any>;
};
/**
 * Chain API для создания реакции
 *
 * Позволяет удобно создавать реакции с декларативными фильтрами.
 *
 * @template C - схема контекста
 * @template S - строковые ключи состояний
 * @template Core - тип core объекта
 *
 * @example
 * ```typescript
 * const chain = reaction({
 *   title: "Обработка сообщений",
 *   description: "Обрабатывает входящие сообщения"
 * })
 *   .filter({
 *     tag: "user",
 *     op: "replace",
 *     path: "/context"
 *   })
 *   .equal(({ update, context, patch }) => {
 *     update({
 *       lastMessage: patch.value,
 *       messageCount: context.messageCount + 1
 *     })
 *   })
 * ```
 */
export type ReactionChain<C extends ContextSchema, S extends string, Core = Record<string, any>> = (config?: {
	/** Название реакции */
	title?: string;
	/** Описание реакции */
	description?: string;
}) => {
	/** Добавляет декларативные фильтры */
	filter: (conditions: ReactionFilterConditions) => {
		/** Добавляет функцию обработки события */
		equal: (updateFn: ReactionUpdate<C, S, Core>) => {
			/** Функция фильтрации */
			filter: (args: ReactionFilterArgs) => boolean;
			/** Функция обработки */
			update: ReactionUpdate<C, S, Core>;
			/** Название реакции */
			title: string;
			/** Описание реакции */
			description?: string;
		};
	};
};
/**
 * Цепочка для создания массива реакций
 *
 * Позволяет создавать массив реакций с группировкой по состояниям.
 *
 * @template C - схема контекста
 * @template S - строковые ключи состояний
 * @template Core - тип core объекта
 *
 * @example
 * ```typescript
 * const reactions: ReactionsChain<MyContext, "idle" | "loading"> = (reaction) => [
 *   [
 *     ["idle", "loading"], // Состояния
 *     reaction({ title: "Обработка сообщений" })
 *       .filter({ tag: "user" })
 *       .equal(({ update, patch }) => {
 *         update({ lastMessage: patch.value })
 *       })
 *   ]
 * ]
 * ```
 */
export type ReactionsChain<C extends ContextSchema, S extends string, Core = Record<string, any>> = (reaction: ReactionChain<C, S, Core>) => [
	S[],
	{
		/** Функция фильтрации */
		filter: (args: ReactionFilterArgs) => boolean;
		/** Функция обработки */
		update: ReactionUpdate<C, S, Core>;
		/** Название реакции */
		title: string;
		/** Описание реакции */
		description?: string;
	}
][];
/**
 * MetaFor — фабрика для создания web-компонента-актора конечного автомата
 * @param tag - уникальный тег web-компонента
 * @returns chain API: context() -> states() -> actions()
 */
export declare function MetaFor(tag: string): {
	/**
	 * Регистрирует схему контекста для автомата.
	 *
	 * Контекст содержит только простые типы данных. Сложные объекты храните в core.
	 *
	 * @param schema Функция, принимающая types и возвращающая объект-схему контекста
	 * @returns chain API для вызова .states(...)
	 *
	 * @example
	 * ```typescript
	 * .context((types) => ({
	 *   userId: types.number.required(0),
	 *   userName: types.string.required("Anonymous"),
	 *   selectedIds: types.array.required([]),
	 *   isLoading: types.boolean.required(false),
	 *   theme: types.enum.required(["light", "dark"]),
	 * }))
	 * ```
	 */
	context<C extends ContextSchema>(schema: (types: ContextTypes) => C): {
		/**
		 * Регистрирует переходы автомата между состояниями.
		 *
		 * @param states Объект, где ключ — имя состояния, а значение — карта возможных переходов (ключ — следующее состояние, значение — условия или данные перехода).
		 * Пример:
		 * ```ts
		 * .states({
		 *   guest: { user: { name: "Пользователь" } },
		 *   user: { guest: {} },
		 * })
		 * ```
		 * @returns chain API для вызова .actions(...)
		 */
		states<S extends string>(states: StatesConfig<S, C>): {
			core(core?: Record<string, any>): {
				/**
				 * Регистрирует процессы автомата для нужных состояний.
				 *
				 * @param process Функция, принимающая process — фабрику chain API для описания процессов.
				 * Возвращает объект, где ключ — имя состояния (только для тех, где нужны процессы), а значение — chain-объект с обработчиками.
				 *
				 * Пример:
				 * ```ts
				 * .actions(process => ({
				 *   guest: process({ title: "guest_process", description: "Процесс для гостя" })
				 *     .action(({ context }) => { ... })
				 *     .success(({ update, data }) => update({ ... }))
				 *     .error(({ update, error }) => update({ ... })),
				 *   // для других состояний можно не указывать процесс, если он не требуется
				 * }))
				 * ```
				 *
				 * @returns Объект с процессами только для нужных состояний
				 */
				processes(process?: ActionsDeclaration<C, S>): {
					/**
					 * Регистрирует карту реакций для автомата.
					 * @param reaction Функция (filter => декларация), где декларация — массив кортежей [string[], { update, filter, title }]
					 * @returns chain API для вызова .view(...)
					 */
					reactions(reaction?: ReactionsChain<C, S>): {
						view(view?: ViewConfig<C, S>): void;
					};
				};
			};
		};
	};
};

export {};
